### ISSUE TITLE
Can't compile it..

### ISSUE THREAD

**Issue by oderwat** [marcelarie/nu-alias-converter#1]
I have no clue about Rust, so this may be my fault, but I get:

![image](https://github.com/user-attachments/assets/348c8382-4985-49ef-8dc0-157b99a0aeed)

I actually just wanted to see what it will do with something like this: `alias cowlol = cowsay hello | lolcat` because pipes are not supported in aliases AFAIK.

**Comment by marcelmanz** [comment]
Hi @oderwat! Seems that the issue comes from one of the dependencies, will try to find a solution as soon as possible.

And please tell me the result of these two commands:

- `rustup show`
- `rustc --version`

**Comment by marcelmanz** [comment]
The issue should be fixed after https://github.com/marcelarie/nu-alias-converter/commit/8ae55428c002a746b0cae0a88aa0a7777646dac3. 

Please try to reinstall again with:
```bash
cargo install nu-alias-converter
```

**Comment by oderwat** [comment]
I tried installing with cargo first. I do not use rustup but Nix. Versions are in the image:

<img width="207" alt="image" src="https://github.com/user-attachments/assets/f4540078-03aa-4c75-b4fe-2e48ecbfe153" />

Your fix worked. But it seems that the tool is not doing any conversions. I guess your scope was more on using the parsers than to actually make a converter like `alias x=a && b` `alias x = a; b` and more complicated stuff like rewriting an alias with pipes into the alias as a custom command / function.

TY for what it is :)

**Comment by marcelmanz** [comment]
>  I guess your scope was more on using the parsers than to actually make a converter 

Yes, the main goal was to create a tool that "sources" Bash aliases directly in Nushell with minimal overhead. It converts the syntax of the alias declaration and it checks each alias content. If the content of the alias is not valid Nushell code, it comments out the line, with the Nushell compile error, so you can review and manually convert it.

Here a couple of examples:
```
# alias ggpull = git pull origin $(git symbolic-ref --short HEAD) # Errors: Parse mismatch during operation.
# alias gpdw = git push && sc deploy workers # Errors: The '&&' operator is not supported in Nushell
```

For now it's more a migration helper than a language converter.

I’ve considered enhancing the tool in the future to automatically convert the Bash code inside each alias to Nushell code. For now, though, it works well enough for my needs. :)

Thanks for trying it out! If you have any request or ideas that you think will make the tool better, please share them, maybe I sparks my inspiration haha
